deployment:
  tasks:
    - export DEPLOY_PATH=/home/mbp5i4lxqyhm/public_html/system.idzmirkidshub.com
    - /bin/cp -r . $DEPLOY_PATH
    - cd $DEPLOY_PATH
    - /usr/local/bin/php /usr/local/bin/composer install --no-dev --prefer-dist --optimize-autoloader
    - /bin/chmod -R 755 $DEPLOY_PATH
    - /bin/chmod -R 775 $DEPLOY_PATH/storage
    - /bin/chmod -R 775 $DEPLOY_PATH/bootstrap/cache
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan view:clear
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - echo "Deployment to $DEPLOY_PATH complete."
